{% set python_min = '3.10' %}
{% set name = "oop-ext" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 266f5bdcb8ad9f44e3395826f60540c2e7da7710b9f0d6d721037869d1daa992

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - attrs
    - python >={{ python_min }}

test:
  imports:
    - oop_ext
    - oop_ext.foundation
    - oop_ext.interface
  requires:
    - mypy
    - pytest
    - pytest-mock
    - python {{ python_min }}
  commands:
    - pytest --pyargs oop_ext

about:
  home: https://github.com/ESSS/oop-ext
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: OOP Extensions is a set of utilities for object oriented programming which is missing on Python core libraries.
  doc_url: https://oop-ext.readthedocs.io/
  dev_url: https://github.com/ESSS/oop-ext

extra:
  recipe-maintainers:
    - gcardozo123
    - lincrosenbach
    - kfasolin
    - nicoddemus
